language: node_js

node_js:
  - '8'

branchs:
  only:
  - master

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - 'node_modules'

script:
  - npm run lint
  - npm run unit
  - npm run build

after_script:
  - npm config set registry http://registry.npmjs.org
  - npm config set Username 'owlaford'
  - npm config set Password '${GT_PSWD}'
  - npm config set Email 'owlaford@gmail.com'
  - npm publish